In [1]:
import numpy as np
def Gauss_elimination(a,b):
    A=a.tolist() 
    B=b.tolist()
    n = len(A)
    B_Orgin=[0] * n
    
    for i in range(1,n):
        for j in range(i,n): 
            G = A[j][i-1]/A[i-1][i-1]
            
            for k in range(i-1,n): 
                A[j][k] = A[j][k] - A[i-1][k]* G
                
            B[j] = B[j]-B[i-1]*G

    for q in range(0,n):
        B_Orgin[q]=B[q]
        
    B[n-1] = B[n-1]/A[n-1][n-1]
    
    
    for i in range(n-2,-1,-1):
        for j in range(n-1,i,-1):
            B[i] = B[i]- A[i][j]*B[j]
        B[i] = B[i]/A[i][i]                 
     
    B_array=np.zeros([len(B_Orgin),1])
    for t in range(0,len(B_Orgin)):
        B_array[t][0]=B_Orgin[t]
    B_List=B_array.tolist()
    
    UT_array=augMatrix(A,B_List)
     
    print_UT_array(UT_array,B)
    
    



def print_UT_array(a,b):
    matrix=np.array(a)
    matrix_2=np.array(b)
    print("upper triangular matrix:")
    print(matrix.round(1))
    print("x:")
    matrix_22=matrix_2.round(1).tolist()
    print(matrix_22)
    
def augMatrix(x, y):
    return [AA + bb for AA, bb in zip(x,y)]




In [2]:
a = np.array([[1, 2, 3],[3, 4, 5],[3, 5, 5]])
y = np.array([2, 2, 5])
Gauss_elimination(a,y)

upper triangular matrix:
[[ 1.  2.  3.  2.]
 [ 0. -2. -4. -4.]
 [ 0.  0. -2.  1.]]
x:
[-2.5, 3.0, -0.5]


In [3]:
a = np.array([[1, 2, 3, 4],[5, 4, 3, 2],[2, 1, 2, 4],[2, 1, 3, 4]])
y = np.array([4, 8, 5, 6])
Gauss_elimination(a,y)

upper triangular matrix:
[[  1.    2.    3.    4.    4. ]
 [  0.   -6.  -12.  -18.  -12. ]
 [  0.    0.    2.    5.    3. ]
 [  0.    0.    0.   -2.5  -0.5]]
x:
[1.4, -0.6, 1.0, 0.2]
