In [1]:
import numpy as np

def LU(A,B):
    A=A.astype(float)#先轉成浮點數
    B=B.astype(float)
    n = len(A)       #A的長度

    L=np.zeros((n,n)) #造一個空矩陣
    for i in range(0,n):    #造一個對角矩陣
        for j in range(0, n):*
            if i==j:        #如果在對角線上則為一
                L[j][i]=1
            else:
                L[j][i]=0   #不是則為零
    for i in range(1,n):    #計算上三角矩陣\與下三角矩陣
        for j in range(i,n):        
            G = A[j][i-1]/A[i-1][i-1]#計算行間的倍率差
            L[j][i-1]=G              #將倍率丟進下三角
            for k in range(i-1,n): 
                A[j][k] = A[j][k] - A[i-1][k]* G #計算上三角矩陣
            B[j] = B[j]-B[i-1]*G                 #計算上三角矩陣中的Y
    U=A.round(1)  #控制上矩陣小數點位數為小數點後一位
    L=L.round(1)  #控制下矩陣小數點位數為小數點後一位
    print('u_matrix:')#列印上與下三角矩陣
    print(U)
    print('l_matrix:')
    print(L)
    
    return [U,L]  #以list方式回傳


def Sol(U,L,y):             #輸出X的function
    X=np.linalg.inv(L).dot(y) #下矩陣dot y
    Z=np.linalg.inv(U).dot(X) #上矩陣再去dot他們 
    Z=Z.round(1).tolist()     #轉成list
    print("x:")
    print(Z)

In [2]:
a = np.array([[1, 2, 3],[3, 4, 5],[3, 5, 5]])
y = np.array([2, 2, 5])
U,L=LU(a,y)
Sol(U,L,y)
 
    

u_matrix:
[[ 1.  2.  3.]
 [ 0. -2. -4.]
 [ 0.  0. -2.]]
l_matrix:
[[1.  0.  0. ]
 [3.  1.  0. ]
 [3.  0.5 1. ]]
x:
[-2.5, 3.0, -0.5]


In [3]:
a = np.array([[1, 2, 3, 4],[5, 4, 3, 2],[2, 1, 2, 4],[2, 1, 3, 4]])
y = np.array([4, 8, 5, 6])
U,L=LU(a,y)
Sol(U,L,y)
 

u_matrix:
[[  1.    2.    3.    4. ]
 [  0.   -6.  -12.  -18. ]
 [  0.    0.    2.    5. ]
 [  0.    0.    0.   -2.5]]
l_matrix:
[[1.  0.  0.  0. ]
 [5.  1.  0.  0. ]
 [2.  0.5 1.  0. ]
 [2.  0.5 1.5 1. ]]
x:
[1.4, -0.6, 1.0, 0.2]


In [ ]:
a = np.array([[1, 2, 3, 4],[5, 4, 3, 2],[2, 1, 2, 4],[2, 1, 3, 4]])
y = np.array([4, 8, 5, 6])
U,L=LU(a,y)
Sol(U,L,y)