In [3]:
import numpy as np

In [4]:
def gauss_jordan_elimination(a,b):
    print("diagonal matrix:")
    A=a.astype(float)  #轉成浮點數矩陣
    B=b.astype(float) 
    
    n = len(A)  #A陣列的column數
 
    for i in range(1,n):
        for j in range(i,n): 
            G = A[j][i-1]/A[i-1][i-1]      # 計算要消掉的倍數 
            for k in range(i-1,n):        #  從i-1行開始消
                A[j][k] = A[j][k] - A[i-1][k]* G #對A消去           
            B[j] = B[j]-B[i-1]*G                 #對B消去
#以上為上三角矩陣############################################
    
    final_M=np.zeros((n,n+1))
    for i in range(0,n):      #將A與B結合為增廣矩陣
        for j in range(0,n+1):
            if(j==n):
                final_M[i][j]=B[i]
            else:
                final_M[i][j]=A[i][j]
    
    for i in range(0,n):            #再來進行削減
        if(final_M[i][i]!= 1):      #當第A[i][i]項不等於一時,將第i列的所有值(先對自己的列化減)
             final_M[i]=final_M[i]/final_M[i][i] 
   
    for j in range(0,n):
        for k in range(j,n-1):
              final_M[j] =final_M[j]-final_M[k+1]*(final_M[j][k+1]/ final_M[k+1][k+1])#再來進行列與列之間的消去
                
    return final_M       


def Find_X(x):  #得到X的function
    
    N=len(x)  #x矩陣大小 
    
    X=np.zeros(N)#建立一個全為零的矩陣
    for i in range(0,N):#取增廣矩陣得最右邊的列為X
        X[i]=x[i][N]
    print("x:")
  
    X=X.round(1)#設定小數點位數
    X=X.tolist()#轉成list
    print(X)

In [5]:
a = np.array([[3,-1,4],[17,2,1],[1,12,-7]])
y = np.array([2,14,54])
x=gauss_jordan_elimination(a,y)
print(x)
Find_X(x)

diagonal matrix:
[[1.         0.         0.         0.05901639]
 [0.         1.         0.         5.57377049]
 [0.         0.         1.         1.84918033]]
x:
[0.1, 5.6, 1.8]
